### PR TITLE
copyright date change to 2020

### PR DESCRIPTION
**Pull request by elaruepa**

### CODE REVIEW

**Review by BradySheehan — CHANGES_REQUESTED** [review]
Why did you title this PR copyright change if the you didn't change the copyright?

What does the website look like with the changed banner? 

To improve the review process, it'd be best to either have shown me the changes "live" or copy a screenshot of the changes into the pull request.

**Comment by elaruepa** [comment]
The banner was a while ago.  The copyright I just did.  It showed on the server when I looked.  Let me retry.  Still some gaps in the steps in my notes.

**Comment by elaruepa** [comment]
Screen Shot 2020-01-15 at 12 24 08 PM

**Review by BradySheehan — CHANGES_REQUESTED** [review]
I know you said you changed the copyright. I suggest you do a `git add /path/to/file` then a `git commit -m "fixed copyright date", and then a `git push` so that we can see the copyright change.

**Comment by elaruepa** [comment]
hmmm.  Looks like I did do all those commands you suggested before I did the initial PR.  
Screen Shot 2020-01-20 at 6 44 06 PM

**Comment by elaruepa** [comment]
Copyright date updated.  
Screen Shot 2020-01-29 at 11 43 31 AM

**Comment by BradySheehan** [comment]
There still isn't a change for the copyright date on this pull request..

**Pull request merged**
